title: 개발자 최은석
email: nonjk2@gmail.com
description: TIL 과 WIL 블로그
author: 최은석
baseurl: "/"
url: "https://nonjk2.github.io"

# Social Profiles
twitter_username:
github_username: 최은석
facebook_username:
instagram_username:
linkedin_username:
# Add your google-analytics ID here to activate google analytics
google_analytics: G-43895YHF45 # out your google-analytics code

# Build settings

markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
